version: "3.8"

services:
  k8s-central:
    build: .
    container_name: k8s-central
    ports:
      - "8000:8000"
    volumes:
      # Mount the FOLDER (Safe) instead of the FILE (Crashy)
      - ./k8s-data:/app/data
      - ./k8s-configs:/app/configs
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    restart: unless-stopped
